name: DEPLOY DE SITE COM GITHUB ACTIONS

on:
 push:
   branches: ["main"]
   
permissions: 
 contents: read
 pages: write
 id-token: write

jobs: 
  deploy:
   runs-on: ubuntu-latest

   steps: 
     #atualizado para @av4 (garante compatibilidade)

     - name: configurar o GITHUB pages
       uses: actions/checkout@v4

    #atualizado para @v5
    
     - name: uploads dos arquivos do site 
       uses: actions/configure-pages@v5
        
   #atualização para @v3
     - name: upload dos arq do site 
       uses: actions/upload-pages-artifact@v3
       with:
         path: '.'
   #@v4
     - name: publicar no github
       id: deployment
       uses: actions/deploy-pages@v4
  
